### ISSUE TITLE
Waydroid fails to start of a Jingpad A1 due to InvalidURL error

### ISSUE THREAD

**Issue by jbonomi** [Aarontheissueguy/WaydroidHelper#12]
Looking at wayland log, I see this error: 

`http.client.InvalidURL: URL can't contain control characters. '/vendor/waydroid_arm64/JingPad C1.json' (fount at least ' ')`

Something to do with the space in that file path?

**Comment by Aarontheissueguy** [comment]
Sorry for the long silence, This error is most likely not related to Waydroid Helper but rather a Waydroid issue.
