### ISSUE TITLE
External keyboard strokes are doubled

### ISSUE THREAD

**Issue by usernameallreadytaken** [Aarontheissueguy/WaydroidHelper#17]
When you connect an external keyboard keystrokes are doubled in waydroid.

I believe this is from both waydroid and UB reading the keys. 

Perhaps we can have a switch to disable input in waydroid through subsystem input?

Or can we disable UB from sending keys when waydroid is focused?

**Comment by JamiKettunen** [comment]
I doubt this issue is of any relevance to the Waydroid Helper program itself, should be reported on https://github.com/waydroid/waydroid/issues.

**Comment by JamiKettunen** [comment]
Cannot reproduce with Android 11 images on Waydroid 1.3.3 now available from UT repos with USB keyboard attached via OTG to a Volla Phone 22, I think this issue can be closed.
