### ISSUE TITLE
installer isn't pulling any image for Halium 11

### ISSUE THREAD

**Issue by Idcrafter** [Aarontheissueguy/WaydroidHelper#18]
i have a Halium 11 based Volla phone 22 and waydroid can't find a OTA image for Halium 11 and all i saw is from 9-10 and the /usr/share/waydroid-extra/images folder is too small to fit a custom waydroid image

**Comment by Fuseteam** [comment]
this was because there was no image and no ota channel for halium 11 that changed [yesterday](https://github.com/waydroid/OTA/commit/9468b22103fdd7f9e6018f3eb111eebe17871b22)

**Comment by JamiKettunen** [comment]
I think this issue can be closed now, Halium 11 vendor and Android 11 system images have both been available for a while now even though setting them up on a Halium 11 device such as the Volla Phone 22 still isn't ideal, but there's not much this app can do when package upgrades are already in the works to fix this properly: https://ubports.atlassian.net/browse/YUMI-11

**Comment by JamiKettunen** [comment]
No workaround should be needed anymore since `waydroid` v1.3.3 and `python3-gbinder` v1.1.1 are in UT 16.04 repos even on OTA-24 afaik so this issue can be closed.

**Comment by Fuseteam** [comment]
@maciek134 are you able to close issues? xD
