### ISSUE TITLE
waydroid can't start session on ubuntu touch OTA-24 pixel 3a

### ISSUE THREAD

**Issue by yourchanges** [Aarontheissueguy/WaydroidHelper#23]
here is the log
![1670308394433](https://user-images.githubusercontent.com/492946/205838528-f2af6243-c1da-4eca-a758-5c5ca0240b3b.png)

**Comment by JamiKettunen** [comment]
Duplicate of #22, same solution should work for you.

**Comment by yourchanges** [comment]
ok, I got it worked

**Comment by JamiKettunen** [comment]
No workaround should be needed since `waydroid` v1.3.3 and `python3-gbinder` v1.1.1 are in UT 16.04 repos even on OTA-24 afaik so this issue can be closed.

**Comment by Fuseteam** [comment]
So also duplicate of #18 xd

**Comment by maciek134** [comment]
Different issue, but also fixed
