### ISSUE TITLE
Application freezes on "preparing to download system image" (Fairphone 3)

### ISSUE THREAD

**Issue by tildica** [Aarontheissueguy/WaydroidHelper#34]
The app progresses from installing waydroid -> remounting system -> preparing to download system image, then just freezes completely.
I've tried it on a clean install with no modifications done to the system.

logs (where it starts to go wrong):
```
root@ubuntu-phablet: apt install waydroid python3-gbinder -y
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
biometryd-bin : Depends: libbiometry1 (= 0.0.3+ubports+a9~20221201182223.8~b117479) but it is not going to be installed
qml-module-biometryd : Depends: libbiometry1 (= 0.0.3+ubports+a9~20221201182223.8~b117479) but it is not going to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution)
root@ubuntu-phablet: remounting filesystem to ro
mount -o remount,ro /
root@ubuntu-phablet: Initializing waydroid (downloading lineage)
Download status running
waydroid init
bash: waydroid: command not found
```

Looks like it fails to install due to dependency conflicts when trying to install the `waydroid` package.
`apt-get -f install` also fails with a `trying to overwrite '/usr/lib/aarch64-linux-gnu/libbiometryd.so.1.0.1', which is also in package libbiometryd1:arm64 0.0.0+ubports+0~2022...`

Device: Fairphone 3, OTA-24, Halium 10
WayDroid Helper v2.0.5

**Comment by maciek134** [comment]
Does this still happen? And were you using things like `ubports-qa` or messing with a read-write filesystem in any other way?

**Comment by tildica** [comment]
Yeah, seems like the issue was resolved with the latest OTA so I'll close this issue.
