### ISSUE TITLE
Focal version still limited to 4 digit pin

### ISSUE THREAD

**Issue by stekalb** [Aarontheissueguy/WaydroidHelper#47]
on Focal system settings defining a pin with more than 4 digits is supported. 
However the popup in waydroid helper supports only 4 digits. So if you have a pin with more than 4 digits you can't authenticate for admin actions in waydroid helper

**Comment by maciek134** [comment]
Aaand the fix was even contributed a while ago (#44), I remember waiting for something else to make a release but I'll take a look at the repo and will try to push a new version soon.

**Comment by symbuzzer** [comment]
Any news about release sir?

**Comment by maciek134** [comment]
Released a while back

**Comment by maciek134** [comment]
Released a while back
