### ISSUE TITLE
GPS Fix lost upon startup of Waydroid

### ISSUE THREAD

**Issue by boroli** [Aarontheissueguy/WaydroidHelper#50]
Once Waydroid is started the GPS signal is lost. I checked while PureMaps and Sensorsstatus was running, and once I started Waydroid I stopped getting any GPS update. I was outdoors and had a clear GPS signal before.
Which is odd, as Waydroid is (not yet) supporting GPS by default: https://github.com/waydroid/waydroid/issues/226
Or is the GPS ttyUSB taken over by Waydroid upon startup?

I'm running a VollaPhone 22 on the latest stable focal build.

**Comment by JamiKettunen** [comment]
There's pretty much nothing waydroid helper has to do / could do with this issue. On 20.04 OTA-2 which you were running at the time this was a known issue and should've been fixed withhttps://gitlab.com/ubports/development/core/location-service/-/merge_requests/25 which is now part of 20.04 OTA-3

**Comment by boroli** [comment]
Thanks for the explanation. I updated now to OTA-3, and see the new behaviour. Closing this now.
