### ISSUE TITLE
Hide app feature doesnt work on focal

### ISSUE THREAD

**Issue by symbuzzer** [Aarontheissueguy/WaydroidHelper#58]
Cant hide android apps icons from UT launcher

**Comment by symbuzzer** [comment]
truncate -s 0 waydroid.com.android.google.gms.desktop

This command works

**Comment by ZeemSquirrel** [comment]
Also experiencing this issue, FP4 OTA-5. Tapping the button to hide icons does nothing.

**Comment by tmtvl** [comment]
A potential reason for this issue may be that the `NoDisplay=true` line gets added under the app_settings desktop action rather than under the desktop entry.

**Comment by ZeemSquirrel** [comment]
> A potential reason for this issue may be that the `NoDisplay=true` line gets added under the app_settings desktop action rather than under the desktop entry.

This appears to be accurate. It is possible to manually enter 'NoDisplay=true' under the first block of parameters in the .desktop file and have the icon be hidden. Waydroid Helper adds this line at the very bottom which has no effect.

**Comment by Fuseteam** [comment]
i can confirm this now, i can hide the calculator app which seems to have the following structure:
```
[Desktop Entry]
Type=Application
Name=Calculator
Exec=waydroid app launch com.android.calculator2
Icon=/home/phablet/.local/share/waydroid/data/icons/com.android.calculator2.png
X-Purism-FormFactor=Workstation;Mobile;
X-Lomiri-Supported-Orientations=portrait;               
```
but not for whatsapp which has the following structure
```
[Desktop Entry]
Type=Application
Name=WhatsApp
Exec=waydroid app launch com.whatsapp
Icon=/home/phablet/.local/share/waydroid/data/icons/com.whatsapp.png
Categories=X-WayDroid-App;
X-Purism-FormFactor=Workstation;Mobile;
X-Lomiri-Supported-Orientations=portrait;
Actions=app_settings;

[Desktop Action app_settings]
Name=App Settings
Exec=waydroid app intent android.settings.APPLICATION_DETAILS_SETTINGS package:com.whatsapp
Icon=/home/phablet/.local/share/waydroid/data/icons/com.android.settings.png
```

from what i can tell the `NoDisplay` line is added from here https://github.com/Aarontheissueguy/WaydroidHelper/blob/main/src/main.py#L69

so we need to adjust to add it under `[Desktop Entry]` rather than at the very bottom of the file
